server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64 #  https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 4 # https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/animals
    username: root
    password: 123
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
    flyway:
      locations: classpath:db/migration
      enabled: true
      baseline-on-migrate: true


# swagger
springdoc:
  api-docs:
    enabled: true
    path: /doc
  swagger-ui:
    path: /doc.html